Add proxy recommendations
oasisprotocol/sapphire-paratime pull request #313
Opened 2024-05-13 22:36 UTC by aefhm

## Description

Add technical notes on proxies.

2024-05-16 09:16 UTC, matevz requested changes

2024-05-16 09:16 UTC, matevz commented on docs/proxies.md
> +**What are Upgradable Contracts?**
I would use the sub-sub heading for this.

```suggestion
### What are Upgradable Contracts?
```

2024-05-16 09:16 UTC, matevz commented on docs/proxies.md
> +**[EIP-1822]: Universal Upgradeable Proxy Standard (UUPS)**
```suggestion
#### [EIP-1822]: Universal Upgradeable Proxy Standard (UUPS)
```

2024-05-16 09:16 UTC, matevz commented on docs/proxies.md
> +**[EIP-1967]: Standard Proxy Storage Slots**
```suggestion
#### [EIP-1967]: Standard Proxy Storage Slots
```

2024-05-24 18:29 UTC, matevz reviewed
Do you think we should rather rename the chapter to `upgradable.md`? I can't get rid of a feeling that the chapter is about setting up oracles or paymasters or proxy nodes at first glance when I see the "Proxies" title. The "Upgradable Contracts" is the title I think it rings the right bell for firstcomers.

2024-05-28 00:01 UTC, aefhm commented
> Do you think we should rather rename the chapter to `upgradable.md`? I can't get rid of a feeling that the chapter is about setting up oracles or paymasters or proxy nodes at first glance when I see the "Proxies" title. The "Upgradable Contracts" is the title I think it rings the right bell for firstcomers.

I kind of want to 🤔. I hear you on the notion of proxy nodes. My concern with "Upgradeable Contracts" would be that the deterministic deploys are "Clones" so to speak with regards to OpenZeppelin [terminology](https://docs.openzeppelin.com/contracts/4.x/api/proxy). Perhaps "Deployment Customization" or "Upgradable and Deterministic Contracts?"

2024-05-29 11:15 UTC, matevz approved these changes
Excellent!

2024-05-29 16:47 UTC, merged